services:
  mt5:
    build: .
    image: gmag11/metatrader5_vnc
    container_name: mt5
    security_opt:
      - label=disable
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
      - 8001:8001
    env_file:
      - .env

